baseURL = "https://suphiro-arch.github.io/NA-kunnskap/"
languageCode = "nb-no"
title = "Nasjonal arkitektur"

[params]
  siteDescription = "Testflate for innhold om nasjonal arkitektur, prinsipper, kapabiliteter og ressursoversikt."
  feedbackEmail = "nasjonalarkitektur@digdir.no"
  githubRepoURL = "https://github.com/suphiro-arch/NA-kunnskap"
  githubIssuesURL = "https://github.com/suphiro-arch/NA-kunnskap/issues/new"

[markup]
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 3
    ordered = false
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
